name: data_integration_project
channels:
  - conda-forge
dependencies:
  - geopandas=0.10.2
  - ipywidgets=7.6.5
  - notebook=6.4.8
  - matplotlib=3.5.1
  - numpy=1.22.1
  - pandas=1.4.0
  - pip=21.3.1
  - plotly=5.5.0
  - psycopg2=2.9.3
  - python=3.10.2
  - python-levenshtein=0.12.2
  - seaborn=0.11.2
  - sqlalchemy=1.4.31
  - xlrd=2.0.1
  - pip:
    - pywebio==1.5.2
    - sparql_dataframe==0.4
